plugins {
    id 'com.android.application'
}

android {
    namespace 'org.diplomanotes.polytechnicstudyhub'
    compileSdk 35

    defaultConfig {
        applicationId 'org.diplomanotes.polytechnicstudyhub'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '1.0.4'
    }

    buildFeatures {
        buildConfig true
    }

    packaging {
        resources {
            pickFirsts += [
                'META-INF/androidx.arch.core_core-runtime.version',
                'META-INF/androidx.drawerlayout_drawerlayout.version',
                'META-INF/androidx.lifecycle_lifecycle-livedata-core.version',
                'META-INF/androidx.lifecycle_lifecycle-runtime.version',
                'META-INF/androidx.lifecycle_lifecycle-viewmodel-savedstate.version',
                'META-INF/androidx.lifecycle_lifecycle-viewmodel.version'
            ]
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
}
