#!/usr/bin/env python3
"""Prune stale GitHub Actions caches while preserving recent cache families.

The repository's largest caches are generated by GitHub CodeQL rather than by
our static-site build. This script keeps the newest KEEP_PER_FAMILY entries for
each normalized cache-key family and deletes older entries through the GitHub
Actions cache API.
"""
from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request

REPO = os.environ.get("GITHUB_REPOSITORY", "")
TOKEN = os.environ.get("GH_TOKEN", "")
KEEP_PER_FAMILY = int(os.environ.get("KEEP_PER_FAMILY", "2"))
API_ROOT = "https://api.github.com"


def api(method: str, path: str, payload: dict | None = None) -> dict:
    url = API_ROOT + path
    body = None if payload is None else json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(url, method=method, data=body)
    request.add_header("Accept", "application/vnd.github+json")
    request.add_header("X-GitHub-Api-Version", "2022-11-28")
    request.add_header("Authorization", f"Bearer {TOKEN}")
    if body is not None:
        request.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(request, timeout=30) as response:
        if response.status == 204:
            return {}
        return json.loads(response.read().decode("utf-8"))


def family(key: str) -> str:
    # GitHub-generated CodeQL keys end with a long hexadecimal fingerprint.
    return re.sub(r"-[0-9a-f]{32,}$", "", key)


def main() -> int:
    if not REPO or not TOKEN:
        print("GITHUB_REPOSITORY and GH_TOKEN are required", file=sys.stderr)
        return 2
    if KEEP_PER_FAMILY < 1:
        print("KEEP_PER_FAMILY must be at least 1", file=sys.stderr)
        return 2

    caches: list[dict] = []
    for page in range(1, 11):
        query = urllib.parse.urlencode({"per_page": 100, "page": page})
        result = api("GET", f"/repos/{REPO}/actions/caches?{query}")
        batch = result.get("actions_caches", [])
        caches.extend(batch)
        if len(batch) < 100:
            break

    grouped: dict[str, list[dict]] = {}
    for cache in caches:
        grouped.setdefault(family(cache.get("key", "")), []).append(cache)

    to_delete: list[dict] = []
    for entries in grouped.values():
        entries.sort(key=lambda item: item.get("created_at", ""), reverse=True)
        to_delete.extend(entries[KEEP_PER_FAMILY:])

    print(json.dumps({
        "repository": REPO,
        "totalCaches": len(caches),
        "cacheFamilies": len(grouped),
        "keepPerFamily": KEEP_PER_FAMILY,
        "scheduledForDeletion": len(to_delete),
        "retainedIds": [entry["id"] for entries in grouped.values() for entry in sorted(entries, key=lambda item: item.get("created_at", ""), reverse=True)[:KEEP_PER_FAMILY]],
    }, indent=2))

    failures = 0
    for cache in to_delete:
        try:
            api("DELETE", f"/repos/{REPO}/actions/caches/{cache['id']}")
            print(f"deleted id={cache['id']} key={cache.get('key', '')}")
        except urllib.error.HTTPError as error:
            failures += 1
            print(f"failed id={cache['id']} status={error.code}", file=sys.stderr)

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
